#!/bin/sh

if [ "$BT_TRACKER" = "false" ]; then
	exit 0
fi

if [ -n "$BT_TRACKER_URL" ]; then
	url="$BT_TRACKER_URL"
else
	url="https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt"
fi

wget --spider "$url" 2>/dev/null

if [ $? -ne 0 ]; then
    echo "$(date +'%Y-%m-%d %H:%M:%S') Unavailable: $url" > /config/log/bt-tracker/last.log
	exit 1
fi

list="$(wget -qO- "$url" | awk NF | sed ':a;N;s/\n/,/g;ta')"

uuid="$(cat /proc/sys/kernel/random/uuid)"

if [ -n "$SECRET" ]; then
    token="$SECRET"
elif [ -n "$SECRET_FILE" ] && [ -r "$SECRET_FILE" ]; then
    token="$(cat "$SECRET_FILE")"
fi

json='{"jsonrpc":"2.0","id":"'$uuid'","method":"aria2.changeGlobalOption","params":["token:'$token'",{"bt-tracker":"'$list'"}]}'

if [ -n "$(grep ^rpc-secure=true /config/aria2.conf)" ]; then
	scheme="https"
else
	scheme="http"
fi

curl --silent --insecure --header "Content-type: application/json" --data "$json" "${scheme}://localhost:6800/jsonrpc" >/dev/null 2>&1

exitcode=$?
if [ $exitcode -eq 0 ]; then
    echo "$(date +'%Y-%m-%d %H:%M:%S') Successfull" > /config/log/bt-tracker/last.log
	exit 0
else
	echo "$(date +'%Y-%m-%d %H:%M:%S') Error [$exitcode]" > /config/log/bt-tracker/last.log
	exit 1
fi
