#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

usermod -o -u "$PUID" abc
groupmod -o -g "$PGID" abc

echo "PUID: $(id -u abc)"
echo "PGID: $(id -g abc)"

chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
