#!/usr/bin/with-contenv bash

if [ ! -f /config/aria2.conf ]; then
    cp /defaults/aria2.conf /config/aria2.conf

    if [ -n "$SECRET" ]; then
        echo "rpc-secret=$SECRET" >> /config/aria2.conf
    elif [ -n "$SECRET_FILE" ] && [ -r "$SECRET_FILE" ]; then
        echo "rpc-secret=$(cat "$SECRET_FILE")" >> /config/aria2.conf
    fi

    if [ -n "$RPC_CERT" ] && [ -n "$RPC_KEY" ]; then
		if [ -r "$RPC_CERT" ] && [ -r "$RPC_KEY" ]; then
			echo "rpc-secure=true" >> /config/aria2.conf 
			echo "rpc-certificate=$RPC_CERT" >> /config/aria2.conf
			echo "rpc-private-key=$RPC_KEY" >> /config/aria2.conf
		else
			echo "[cont-init.d] rpc-certificate or rpc-private-key inaccessible"
		fi
    fi

    if  [ -n "$FILE_ALLOCATION" ]; then
        case "$FILE_ALLOCATION" in
            none|prealloc|trunc|falloc)
                sed -i "/file-allocation/s|^.*$|file-allocation=$FILE_ALLOCATION|" /config/aria2.conf
            ;;
        esac
    fi

    if [ "$IPV6" = "true" ]; then
        sed -i "/disable-ipv6/s|^.*$|disable-ipv6=false|" /config/aria2.conf
    fi
	
    if [ "$BT_SEEDING" = "false" ]; then
		sed -i "/seed-time/s|^.*$|seed-time=0|" /config/aria2.conf
	fi
fi

# create directories
mkdir -p \
	/config/log/{aria2,bt-tracker} \
	/data

# create files
touch \
	/config/log/{aria2/aria2.log,bt-tracker/last.log} \
	/config/aria2.session \
	/config/netrc

# permissions
chown -R abc:abc /config
chmod -R +r /config/log
chmod 0600 /config/netrc
chmod -R 0644 /etc/logrotate.d
chmod +x /etc/periodic/daily/bt-tracker
