#!/usr/bin/with-contenv bash

(
	until [ -n "$(ps aux | grep aria2c | grep -v grep)" ]; do
		sleep 5s
	done

	/etc/periodic/daily/bt-tracker
) &

exec \
	s6-setuidgid abc aria2c --conf-path=/config/aria2.conf --log=/config/log/aria2/aria2.log >/dev/null 2>&1
